public	directors	postgres	\N	t	f	t	f
public	movie_genres	postgres	\N	t	f	t	f
public	genres	postgres	\N	t	f	t	f
public	movies	postgres	\N	t	f	t	f
pg_catalog	pg_statistic	postgres	\N	t	f	f	f
pg_catalog	pg_type	postgres	\N	t	f	f	f
public	django_migrations	postgres	\N	t	f	f	f
pg_catalog	pg_foreign_table	postgres	\N	t	f	f	f
pg_catalog	pg_authid	postgres	pg_global	t	f	f	f
public	django_content_type	postgres	\N	t	f	t	f
public	auth_permission	postgres	\N	t	f	t	f
public	auth_group	postgres	\N	t	f	t	f
public	auth_group_permissions	postgres	\N	t	f	t	f
pg_catalog	pg_statistic_ext_data	postgres	\N	t	f	f	f
public	auth_user_groups	postgres	\N	t	f	t	f
public	auth_user_user_permissions	postgres	\N	t	f	t	f
public	django_admin_log	postgres	\N	t	f	t	f
public	auth_user	postgres	\N	t	f	t	f
public	django_session	postgres	\N	t	f	f	f
pg_catalog	pg_user_mapping	postgres	\N	t	f	f	f
pg_catalog	pg_subscription	postgres	pg_global	t	f	f	f
pg_catalog	pg_attribute	postgres	\N	t	f	f	f
pg_catalog	pg_proc	postgres	\N	t	f	f	f
pg_catalog	pg_class	postgres	\N	t	f	f	f
pg_catalog	pg_attrdef	postgres	\N	t	f	f	f
pg_catalog	pg_constraint	postgres	\N	t	f	f	f
pg_catalog	pg_inherits	postgres	\N	t	f	f	f
pg_catalog	pg_index	postgres	\N	t	f	f	f
pg_catalog	pg_operator	postgres	\N	t	f	f	f
pg_catalog	pg_opfamily	postgres	\N	t	f	f	f
pg_catalog	pg_opclass	postgres	\N	t	f	f	f
pg_catalog	pg_am	postgres	\N	t	f	f	f
pg_catalog	pg_amop	postgres	\N	t	f	f	f
pg_catalog	pg_amproc	postgres	\N	t	f	f	f
pg_catalog	pg_language	postgres	\N	t	f	f	f
pg_catalog	pg_largeobject_metadata	postgres	\N	t	f	f	f
pg_catalog	pg_aggregate	postgres	\N	t	f	f	f
pg_catalog	pg_statistic_ext	postgres	\N	t	f	f	f
pg_catalog	pg_rewrite	postgres	\N	t	f	f	f
pg_catalog	pg_trigger	postgres	\N	t	f	f	f
pg_catalog	pg_event_trigger	postgres	\N	t	f	f	f
pg_catalog	pg_description	postgres	\N	t	f	f	f
pg_catalog	pg_cast	postgres	\N	t	f	f	f
pg_catalog	pg_enum	postgres	\N	t	f	f	f
pg_catalog	pg_namespace	postgres	\N	t	f	f	f
pg_catalog	pg_conversion	postgres	\N	t	f	f	f
pg_catalog	pg_depend	postgres	\N	t	f	f	f
pg_catalog	pg_database	postgres	pg_global	t	f	f	f
pg_catalog	pg_db_role_setting	postgres	pg_global	t	f	f	f
pg_catalog	pg_tablespace	postgres	pg_global	t	f	f	f
pg_catalog	pg_auth_members	postgres	pg_global	t	f	f	f
pg_catalog	pg_shdepend	postgres	pg_global	t	f	f	f
pg_catalog	pg_shdescription	postgres	pg_global	t	f	f	f
pg_catalog	pg_ts_config	postgres	\N	t	f	f	f
pg_catalog	pg_ts_config_map	postgres	\N	t	f	f	f
pg_catalog	pg_ts_dict	postgres	\N	t	f	f	f
pg_catalog	pg_ts_parser	postgres	\N	t	f	f	f
pg_catalog	pg_ts_template	postgres	\N	t	f	f	f
pg_catalog	pg_extension	postgres	\N	t	f	f	f
pg_catalog	pg_foreign_data_wrapper	postgres	\N	t	f	f	f
pg_catalog	pg_foreign_server	postgres	\N	t	f	f	f
pg_catalog	pg_policy	postgres	\N	t	f	f	f
pg_catalog	pg_replication_origin	postgres	pg_global	t	f	f	f
pg_catalog	pg_default_acl	postgres	\N	t	f	f	f
pg_catalog	pg_init_privs	postgres	\N	t	f	f	f
pg_catalog	pg_seclabel	postgres	\N	t	f	f	f
pg_catalog	pg_shseclabel	postgres	pg_global	t	f	f	f
pg_catalog	pg_collation	postgres	\N	t	f	f	f
pg_catalog	pg_parameter_acl	postgres	pg_global	t	f	f	f
pg_catalog	pg_partitioned_table	postgres	\N	t	f	f	f
pg_catalog	pg_range	postgres	\N	t	f	f	f
pg_catalog	pg_transform	postgres	\N	t	f	f	f
pg_catalog	pg_sequence	postgres	\N	t	f	f	f
pg_catalog	pg_publication	postgres	\N	t	f	f	f
pg_catalog	pg_publication_namespace	postgres	\N	t	f	f	f
pg_catalog	pg_publication_rel	postgres	\N	t	f	f	f
pg_catalog	pg_subscription_rel	postgres	\N	t	f	f	f
pg_catalog	pg_largeobject	postgres	\N	t	f	f	f
information_schema	sql_parts	postgres	\N	f	f	f	f
information_schema	sql_features	postgres	\N	f	f	f	f
information_schema	sql_implementation_info	postgres	\N	f	f	f	f
information_schema	sql_sizing	postgres	\N	f	f	f	f
