# Generated by Django 5.1.3 on 2024-11-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_movie_cast'),
    ]

    operations = [
    ]
