# Generated by Django 5.1.3 on 2024-12-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_director_table_alter_genre_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_column='genre_name', max_length=255),
        ),
    ]
