# Generated by Django 5.1.3 on 2024-12-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='director_name',
        ),
    ]
