# Generated by Django 5.1.3 on 2024-12-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_rename_name_director_director_name'),
    ]

    operations = [
    ]
