# Generated by Django 5.1.3 on 2024-12-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20241215_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movierating',
            unique_together={('user_id', 'movie_id')},
        ),
        migrations.AddField(
            model_name='movierating',
            name='movie_id',
            field=models.IntegerField(db_column='movie_id', default=0),
        ),
        migrations.AddField(
            model_name='movierating',
            name='user_id',
            field=models.IntegerField(db_column='user_id', default=0),
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='user',
        ),
    ]
