# Generated by Django 5.1.3 on 2024-12-17 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_movierating_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierating',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='movierating',
            name='movie_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.movie'),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
